site:
  name: Hanei JP
  site: 'https://hanei.jp'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: googlesiteverificationid

# Default SEO metadata
metadata:
  title:
    default: "Hanei Inbound Digital | Bridging Japan to the World"
    template: '%s — Hanei JP'
  description: "Hanei is dedicated to empowering Japanese local businesses. We believe that Japan’s local culture is its greatest asset, and we use modern technology to ensure that the world can experience it—without the stress of the language barrier."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Hanei JP
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@saashandle'
    site: '@saashandle'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6
    post: { isEnabled: true, permalink: '/%slug%', robots: { index: true } }
    list: { isEnabled: false, pathname: 'blog', robots: { index: true } }
    category: { isEnabled: false, pathname: 'category', robots: { index: true } }
    tag: { isEnabled: false, pathname: 'tag', robots: { index: false } }
    isRelatedPostsEnabled: false
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics: { id: null }

ui:
  theme: 'light:only'
